### PR TITLE
Update $lastGenTime when generating ULID

### LINKED ISSUE #8: Never updates $lastGenTime
The `$lastGenTime` static property (which is supposed to be used to keep track of whether it's generating a new ULID in the same millisecond) is never updated, so the code path for handling generating a ULID in the same millisecond will never be executed (and there are no tests for this behaviour).

### PR DESCRIPTION
**Pull request by gkralik**
Update `$lastGenTime` with current timestamp when generating a ULID (fixes #8)

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
Thanks for the effort! Could you please add a testcase as well?

**Comment by gkralik** [comment]
Hmm, a testcase for this would need to mock `microtime()` output... I could add a test using the ClockMock class (https://github.com/nicolas-grekas/symfony/blob/master/src/Symfony/Bridge/PhpUnit/ClockMock.php)

**Comment by gkralik** [comment]
The mocking would only work if `microtime(true)` is used, not `\microtime(true)` (as introduced in commit 77d0eb274d933cebaa0ab2e2db26277e7741f3ca)

**Comment by gkralik** [comment]
An alternative might be to use some sort of a `TimeSource` that can be mocked...

**Comment by devrck** [comment]
Use a clock abstraction instead of `microtime()` like https://github.com/lcobucci/clock

**Comment by gkralik** [comment]
A clock abstraction is a good idea, but maybe in a new PR?

**Comment by devrck** [comment]
Sounds good then the other PR needs to be created & merged first before you can merge this one right?

**Comment by gkralik** [comment]
I guess so... I'll try to find time in the next few days.

**Comment by devrck** [comment]
I will see if I can help with that, if not then I leave it to you.

**Pull request closed without merging**
