### PR TITLE
Let GitHub Actions test for PHP 8.0 

### PR DESCRIPTION
**Pull request by bepsvpt**
This pull request updates:
1. test for PHP 8.0
2. update actions/checkout and actions/cache version

actions/cache is following https://github.com/shivammathur/setup-php#cache-composer-dependencies format.

### CODE REVIEW

**Comment by bepsvpt** [comment]
It seems the deprecated warning is caused by older version of phpbench/phpbench. 

I think tests will pass after #28 is merged.

**Comment by robinvdvleuten** [comment]
@bepsvpt could you rebase this PR now that 8.0 support is merged.

**Comment by bepsvpt** [comment]
Hi @robinvdvleuten,

Am I correctly rebasing the master branch?

**Comment by robinvdvleuten** [comment]
@bepsvpt yes that's correct, thank you!

**Comment by robinvdvleuten** [comment]
@bepsvpt thank you for the effort 🙏

**Pull request merged**
