### PR TITLE
Correct toTimestamp

### PR DESCRIPTION
**Pull request by DenisGavrilov**
Issue https://github.com/robinvdvleuten/php-ulid/issues/23

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
Thanks for your PR! Could you make sure that the `toTimestamp()` method returns an integer instead of a float? Also keep the test ULIDs the same.

**Comment by DenisGavrilov** [comment]
Sorry, maybe I don`t understand what need todo.
https://github.com/robinvdvleuten/php-ulid/pull/24/commits/69ede1f810f16e25e96e5cff556133c2d4db7023

**Comment by robinvdvleuten** [comment]
@DenisGavrilov no worries. What I tried to say is that there are already two testcases for the `toTimestamp()` method;

```php
public function testConvertsToTimestamp(): void
{
    $this->assertEquals(1561622862, Ulid::fromString('0001EH8YAEP8CXP4AMWCHHDBHJ')->toTimestamp());
    $this->assertEquals(1561622862, Ulid::fromString('0001eh8yaep8cxp4amwchhdbhj', true)->toTimestamp());
}
```

So as I understand your issue and PR correctly, you're saying that `1561622862` is not a correct timestamp and should be divided by a thousand. 

But when I convert the integer `1561622862` to a date instance, I'll get `06-27-2019 @ 8:07am (UTC)` which looks valid to me. 

Could you comment on your PR why you want to divide it and have a float instead of an integer?

**Comment by DenisGavrilov** [comment]
I devide use Ulid in my project because "All included" :) Unique Id, sortable and CreatedTimestamp. But, when I testing, get incorrect date.
Look result  this code  
`   $ulid = Ulid::generate();               
    var_dump($ulid->toTimestamp());               
    $dt = new \DateTime;                          
    var_dump($dt->setTimestamp($ulid->toTimestamp()));         
    var_dump($dt->setTimestamp($ulid->toTimestamp()/1000));
`

**Comment by robinvdvleuten** [comment]
OK, so I checked it myself and get the following results;

```php
<?php

$ulid = Ulid::fromString('0001EH8YAEP8CXP4AMWCHHDBHJ');

$dt = new \DateTime();
        
var_dump($dt->setTimestamp($ulid->toTimestamp())->format('c'));
var_dump($dt->setTimestamp($ulid->toTimestamp() / 1000)->format('c'));
````

Which gives me the following output;

```bash
ulid.php:6: string(25) "2019-06-27T08:07:42+00:00"
ulid.php:7: string(25) "1970-01-19T01:47:02+00:00"
```

I still come to the conclusion that the current timestamp is definitely correct. And this PR can be closed, thanks for the effort.

**Pull request closed without merging**
